# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GigEViewer.ui'
#
# Created: Sun Feb 12 08:42:44 2012
#      by: PyQt4 UI code generator 4.7.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1078, 676)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(9)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(234, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.hboxlayout1 = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(9)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.Camera = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Camera.sizePolicy().hasHeightForWidth())
        self.Camera.setSizePolicy(sizePolicy)
        self.Camera.setMinimumSize(QtCore.QSize(214, 141))
        self.Camera.setObjectName(_fromUtf8("Camera"))
        self.layoutWidget = QtGui.QWidget(self.Camera)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 28, 189, 92))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridlayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(80, 0))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridlayout.addWidget(self.label_20, 0, 0, 1, 2)
        self.label_rate = QtGui.QLabel(self.layoutWidget)
        self.label_rate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rate.setObjectName(_fromUtf8("label_rate"))
        self.gridlayout.addWidget(self.label_rate, 3, 2, 1, 1)
        self.lImgRate = QtGui.QLabel(self.layoutWidget)
        self.lImgRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lImgRate.setObjectName(_fromUtf8("lImgRate"))
        self.gridlayout.addWidget(self.lImgRate, 2, 2, 1, 1)
        self.lImgCounter = QtGui.QLabel(self.layoutWidget)
        self.lImgCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lImgCounter.setObjectName(_fromUtf8("lImgCounter"))
        self.gridlayout.addWidget(self.lImgCounter, 1, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridlayout.addWidget(self.label_14, 1, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridlayout.addWidget(self.label_12, 2, 0, 1, 2)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridlayout.addWidget(self.label_19, 3, 0, 1, 2)
        self.lPV = QtGui.QLabel(self.layoutWidget)
        self.lPV.setText(_fromUtf8(""))
        self.lPV.setObjectName(_fromUtf8("lPV"))
        self.gridlayout.addWidget(self.lPV, 0, 2, 1, 1)
        self.vboxlayout.addWidget(self.Camera)
        self.Parameters = QtGui.QGroupBox(self.widget)
        self.Parameters.setObjectName(_fromUtf8("Parameters"))
        self.gridlayout1 = QtGui.QGridLayout(self.Parameters)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.label = QtGui.QLabel(self.Parameters)
        self.label.setMinimumSize(QtCore.QSize(65, 0))
        self.label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout2.addWidget(self.label, 0, 0, 1, 1)
        self.leExpTime = QtGui.QLineEdit(self.Parameters)
        self.leExpTime.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leExpTime.setObjectName(_fromUtf8("leExpTime"))
        self.gridlayout2.addWidget(self.leExpTime, 0, 1, 1, 1)
        self.lExpTime = QtGui.QLabel(self.Parameters)
        self.lExpTime.setMinimumSize(QtCore.QSize(35, 0))
        self.lExpTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lExpTime.setObjectName(_fromUtf8("lExpTime"))
        self.gridlayout2.addWidget(self.lExpTime, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.Parameters)
        self.label_3.setMinimumSize(QtCore.QSize(65, 0))
        self.label_3.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout2.addWidget(self.label_3, 1, 0, 1, 1)
        self.leExpPeriod = QtGui.QLineEdit(self.Parameters)
        self.leExpPeriod.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leExpPeriod.setObjectName(_fromUtf8("leExpPeriod"))
        self.gridlayout2.addWidget(self.leExpPeriod, 1, 1, 1, 1)
        self.lExpPeriod = QtGui.QLabel(self.Parameters)
        self.lExpPeriod.setMinimumSize(QtCore.QSize(35, 0))
        self.lExpPeriod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lExpPeriod.setObjectName(_fromUtf8("lExpPeriod"))
        self.gridlayout2.addWidget(self.lExpPeriod, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.Parameters)
        self.label_5.setMinimumSize(QtCore.QSize(65, 0))
        self.label_5.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridlayout2.addWidget(self.label_5, 2, 0, 1, 1)
        self.leGain = QtGui.QLineEdit(self.Parameters)
        self.leGain.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leGain.setObjectName(_fromUtf8("leGain"))
        self.gridlayout2.addWidget(self.leGain, 2, 1, 1, 1)
        self.lGain = QtGui.QLabel(self.Parameters)
        self.lGain.setMinimumSize(QtCore.QSize(35, 0))
        self.lGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lGain.setObjectName(_fromUtf8("lGain"))
        self.gridlayout2.addWidget(self.lGain, 2, 2, 1, 1)
        self.gridlayout1.addLayout(self.gridlayout2, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.Parameters)
        self.ROI = QtGui.QGroupBox(self.widget)
        self.ROI.setVisible(False)
        self.ROI.setObjectName(_fromUtf8("ROI"))
        self.gridlayout3 = QtGui.QGridLayout(self.ROI)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.gridlayout4 = QtGui.QGridLayout()
        self.gridlayout4.setMargin(0)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName(_fromUtf8("gridlayout4"))
        self.label_28 = QtGui.QLabel(self.ROI)
        self.label_28.setMinimumSize(QtCore.QSize(65, 0))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridlayout4.addWidget(self.label_28, 0, 0, 1, 1)
        self.leRoiXStart = QtGui.QLineEdit(self.ROI)
        self.leRoiXStart.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leRoiXStart.setObjectName(_fromUtf8("leRoiXStart"))
        self.gridlayout4.addWidget(self.leRoiXStart, 0, 1, 1, 1)
        self.lRoiXStart = QtGui.QLabel(self.ROI)
        self.lRoiXStart.setMinimumSize(QtCore.QSize(35, 0))
        self.lRoiXStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRoiXStart.setObjectName(_fromUtf8("lRoiXStart"))
        self.gridlayout4.addWidget(self.lRoiXStart, 0, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.ROI)
        self.label_25.setMinimumSize(QtCore.QSize(65, 0))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridlayout4.addWidget(self.label_25, 1, 0, 1, 1)
        self.leRoiXSize = QtGui.QLineEdit(self.ROI)
        self.leRoiXSize.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leRoiXSize.setObjectName(_fromUtf8("leRoiXSize"))
        self.gridlayout4.addWidget(self.leRoiXSize, 1, 1, 1, 1)
        self.lRoiXSize = QtGui.QLabel(self.ROI)
        self.lRoiXSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRoiXSize.setObjectName(_fromUtf8("lRoiXSize"))
        self.gridlayout4.addWidget(self.lRoiXSize, 1, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.ROI)
        self.label_24.setMinimumSize(QtCore.QSize(65, 0))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridlayout4.addWidget(self.label_24, 2, 0, 1, 1)
        self.leRoiYStart = QtGui.QLineEdit(self.ROI)
        self.leRoiYStart.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leRoiYStart.setObjectName(_fromUtf8("leRoiYStart"))
        self.gridlayout4.addWidget(self.leRoiYStart, 2, 1, 1, 1)
        self.lRoiYStart = QtGui.QLabel(self.ROI)
        self.lRoiYStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRoiYStart.setObjectName(_fromUtf8("lRoiYStart"))
        self.gridlayout4.addWidget(self.lRoiYStart, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.ROI)
        self.label_13.setMinimumSize(QtCore.QSize(65, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridlayout4.addWidget(self.label_13, 3, 0, 1, 1)
        self.leRoiYSize = QtGui.QLineEdit(self.ROI)
        self.leRoiYSize.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leRoiYSize.setObjectName(_fromUtf8("leRoiYSize"))
        self.gridlayout4.addWidget(self.leRoiYSize, 3, 1, 1, 1)
        self.lRoiYSize = QtGui.QLabel(self.ROI)
        self.lRoiYSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRoiYSize.setObjectName(_fromUtf8("lRoiYSize"))
        self.gridlayout4.addWidget(self.lRoiYSize, 3, 2, 1, 1)
        self.gridlayout3.addLayout(self.gridlayout4, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.ROI)
        self.Binning = QtGui.QGroupBox(self.widget)
        self.Binning.setEnabled(True)
        self.Binning.setVisible(False)
        self.Binning.setObjectName(_fromUtf8("Binning"))
        self.gridlayout5 = QtGui.QGridLayout(self.Binning)
        self.gridlayout5.setMargin(9)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName(_fromUtf8("gridlayout5"))
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.label_15 = QtGui.QLabel(self.Binning)
        self.label_15.setMinimumSize(QtCore.QSize(65, 0))
        self.label_15.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.hboxlayout2.addWidget(self.label_15)
        self.leBinX = QtGui.QLineEdit(self.Binning)
        self.leBinX.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leBinX.setObjectName(_fromUtf8("leBinX"))
        self.hboxlayout2.addWidget(self.leBinX)
        self.lBinX = QtGui.QLabel(self.Binning)
        self.lBinX.setMinimumSize(QtCore.QSize(35, 0))
        self.lBinX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lBinX.setObjectName(_fromUtf8("lBinX"))
        self.hboxlayout2.addWidget(self.lBinX)
        self.gridlayout5.addLayout(self.hboxlayout2, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.Binning)
        self.Crosses = QtGui.QGroupBox(self.widget)
        self.Crosses.setMinimumSize(QtCore.QSize(0, 100))
        self.Crosses.setObjectName(_fromUtf8("Crosses"))
        self.gridLayout = QtGui.QGridLayout(self.Crosses)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridlayout6 = QtGui.QGridLayout()
        self.gridlayout6.setMargin(0)
        self.gridlayout6.setSpacing(6)
        self.gridlayout6.setObjectName(_fromUtf8("gridlayout6"))
        self.label_2 = QtGui.QLabel(self.Crosses)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout6.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.Crosses)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridlayout6.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.Crosses)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridlayout6.addWidget(self.label_7, 1, 0, 1, 1)
        self.leCross1X = QtGui.QLineEdit(self.Crosses)
        self.leCross1X.setMaximumSize(QtCore.QSize(65, 16777215))
        self.leCross1X.setObjectName(_fromUtf8("leCross1X"))
        self.gridlayout6.addWidget(self.leCross1X, 1, 1, 1, 1)
        self.leCross2X = QtGui.QLineEdit(self.Crosses)
        self.leCross2X.setMaximumSize(QtCore.QSize(65, 16777215))
        self.leCross2X.setObjectName(_fromUtf8("leCross2X"))
        self.gridlayout6.addWidget(self.leCross2X, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.Crosses)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridlayout6.addWidget(self.label_8, 2, 0, 1, 1)
        self.leCross1Y = QtGui.QLineEdit(self.Crosses)
        self.leCross1Y.setMaximumSize(QtCore.QSize(65, 16777215))
        self.leCross1Y.setObjectName(_fromUtf8("leCross1Y"))
        self.gridlayout6.addWidget(self.leCross1Y, 2, 1, 1, 1)
        self.leCross2Y = QtGui.QLineEdit(self.Crosses)
        self.leCross2Y.setMaximumSize(QtCore.QSize(65, 16777215))
        self.leCross2Y.setObjectName(_fromUtf8("leCross2Y"))
        self.gridlayout6.addWidget(self.leCross2Y, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.Crosses)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridlayout6.addWidget(self.label_11, 3, 0, 1, 1)
        self.cbCross1Color = QtGui.QComboBox(self.Crosses)
        self.cbCross1Color.setMaximumSize(QtCore.QSize(65, 16777215))
        self.cbCross1Color.setObjectName(_fromUtf8("cbCross1Color"))
        self.gridlayout6.addWidget(self.cbCross1Color, 3, 1, 1, 1)
        self.cbCross2Color = QtGui.QComboBox(self.Crosses)
        self.cbCross2Color.setMaximumSize(QtCore.QSize(65, 16777215))
        self.cbCross2Color.setObjectName(_fromUtf8("cbCross2Color"))
        self.gridlayout6.addWidget(self.cbCross2Color, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridlayout6, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.Crosses)
        self.Modes = QtGui.QGroupBox(self.widget)
        self.Modes.setVisible(False)
        self.Modes.setObjectName(_fromUtf8("Modes"))
        self.gridlayout7 = QtGui.QGridLayout(self.Modes)
        self.gridlayout7.setMargin(9)
        self.gridlayout7.setSpacing(6)
        self.gridlayout7.setObjectName(_fromUtf8("gridlayout7"))
        self.gridlayout8 = QtGui.QGridLayout()
        self.gridlayout8.setMargin(0)
        self.gridlayout8.setSpacing(6)
        self.gridlayout8.setObjectName(_fromUtf8("gridlayout8"))
        self.label_22 = QtGui.QLabel(self.Modes)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridlayout8.addWidget(self.label_22, 0, 0, 1, 1)
        self.cbImageMode = QtGui.QComboBox(self.Modes)
        self.cbImageMode.setObjectName(_fromUtf8("cbImageMode"))
        self.gridlayout8.addWidget(self.cbImageMode, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.Modes)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridlayout8.addWidget(self.label_23, 1, 0, 1, 1)
        self.cbTriggerMode = QtGui.QComboBox(self.Modes)
        self.cbTriggerMode.setObjectName(_fromUtf8("cbTriggerMode"))
        self.gridlayout8.addWidget(self.cbTriggerMode, 1, 1, 1, 1)
        self.gridlayout7.addLayout(self.gridlayout8, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.Modes)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem1)
        self.bStart = QtGui.QPushButton(self.widget)
        self.bStart.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bStart.setObjectName(_fromUtf8("bStart"))
        self.hboxlayout3.addWidget(self.bStart)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem2)
        self.vboxlayout.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem3)
        self.bStop = QtGui.QPushButton(self.widget)
        self.bStop.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bStop.setObjectName(_fromUtf8("bStop"))
        self.hboxlayout4.addWidget(self.bStop)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem4)
        self.vboxlayout.addLayout(self.hboxlayout4)
        spacerItem5 = QtGui.QSpacerItem(181, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem5)
        self.hboxlayout1.addLayout(self.vboxlayout)
        self.hboxlayout.addWidget(self.widget)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(250, 250))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.frame)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.wImage = QtGui.QWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wImage.sizePolicy().hasHeightForWidth())
        self.wImage.setSizePolicy(sizePolicy)
        self.wImage.setStyleSheet(_fromUtf8("background: dark gray"))
        self.wImage.setObjectName(_fromUtf8("wImage"))
        self.vboxlayout1.addWidget(self.wImage)
        self.hboxlayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.Camera.setTitle(QtGui.QApplication.translate("MainWindow", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "PV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rate.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lImgRate.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lImgCounter.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Counter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Frame Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Display Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.Parameters.setTitle(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Exp Time", None, QtGui.QApplication.UnicodeUTF8))
        self.lExpTime.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Period", None, QtGui.QApplication.UnicodeUTF8))
        self.lExpPeriod.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.lGain.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ROI.setTitle(QtGui.QApplication.translate("MainWindow", "ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "X Start", None, QtGui.QApplication.UnicodeUTF8))
        self.lRoiXStart.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "X Size", None, QtGui.QApplication.UnicodeUTF8))
        self.lRoiXSize.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Y Start", None, QtGui.QApplication.UnicodeUTF8))
        self.lRoiYStart.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Y Size", None, QtGui.QApplication.UnicodeUTF8))
        self.lRoiYSize.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.Binning.setTitle(QtGui.QApplication.translate("MainWindow", "Binning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "X, Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lBinX.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.Crosses.setTitle(QtGui.QApplication.translate("MainWindow", "Crosses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Cross 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Cross 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.Modes.setTitle(QtGui.QApplication.translate("MainWindow", "Modes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Image Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Trigger Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.bStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.bStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

