#! /bin/bash

usage()
{
    echo "Usage:  $0 CameraPV"
    exit -1
}

[ $# != 1 ] && usage

# Image size = 1360 x 1024
w=`expr 280 + 1360`
h=`expr 65 + 1024`
./viewer.pyw --camerapv $1 --width $w --height $h
