#! /bin/bash

usage()
{
    echo "Usage:  $0 CameraPV"
    exit -1
}

[ $# != 1 ] && usage

# Image size = 1390 x 1038
w=`expr 280 + 1388`
h=`expr 65 + 1038`
./viewer.pyw --camerapv $1 --width $w --height $h
