TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and/or install (or just install)
# scripts, cmd, and env files to $(TOP)/scripts

#
#    ALL this stuff moved to $TOP/setupScripts
#

# Create and/or install camera specific environment scripts
#CMD += MantaG033B.env
#CMD += MantaG046B.env
#CMD += MantaG145B.env
#CMD += MantaG146B.env
#CMD += MantaG146C.env
#CMD += MantaG201B.env
#CMD += ProsilicaGC1350C.env

# Create and/or install high level scripts
#CMD += commonPlugins.cmd
#CMD += prosilica.cmd

# Create and/or install plugin scripts
#CMD += pluginColorConvert.cmd
#CMD += pluginFileMPEG.cmd
#CMD += pluginHDF5.cmd
#CMD += pluginImage.cmd
#CMD += pluginJPEG.cmd
#CMD += pluginMagick.cmd
#CMD += pluginMJPG.cmd
#CMD += pluginNetCDF.cmd
#CMD += pluginNexus.cmd
#CMD += pluginOverlay.cmd
#CMD += pluginProcess.cmd
#CMD += pluginROI.cmd
#CMD += pluginStats.cmd
#CMD += pluginTIFF.cmd
#CMD += pluginTransform.cmd

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

