# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prosilica1350.ui'
#
# Created: Thu Jun  9 17:56:14 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_GigEImageViewer(object):
    def setupUi(self, GigEImageViewer):
        GigEImageViewer.setObjectName("GigEImageViewer")
        GigEImageViewer.resize(1590, 1077)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GigEImageViewer.sizePolicy().hasHeightForWidth())
        GigEImageViewer.setSizePolicy(sizePolicy)
        self.image_frame = QtGui.QWidget(GigEImageViewer)
        self.image_frame.setGeometry(QtCore.QRect(6, 30, 1360, 1024))
        self.image_frame.setMinimumSize(QtCore.QSize(1360, 1024))
        self.image_frame.setObjectName("image_frame")
        self.layoutWidget = QtGui.QWidget(GigEImageViewer)
        self.layoutWidget.setGeometry(QtCore.QRect(1370, 30, 213, 1021))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.Camera = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Camera.sizePolicy().hasHeightForWidth())
        self.Camera.setSizePolicy(sizePolicy)
        self.Camera.setObjectName("Camera")
        self.gridlayout = QtGui.QGridLayout(self.Camera)
        self.gridlayout.setObjectName("gridlayout")
        self.cbCamera = QtGui.QComboBox(self.Camera)
        self.cbCamera.setObjectName("cbCamera")
        self.gridlayout.addWidget(self.cbCamera, 0, 0, 1, 2)
        self.label_20 = QtGui.QLabel(self.Camera)
        self.label_20.setObjectName("label_20")
        self.gridlayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_connected = QtGui.QLabel(self.Camera)
        self.label_connected.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_connected.setObjectName("label_connected")
        self.gridlayout.addWidget(self.label_connected, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.Camera)
        self.label_19.setObjectName("label_19")
        self.gridlayout.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_rate = QtGui.QLabel(self.Camera)
        self.label_rate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rate.setObjectName("label_rate")
        self.gridlayout.addWidget(self.label_rate, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.Camera)
        self.label_12.setObjectName("label_12")
        self.gridlayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.lImgRate = QtGui.QLabel(self.Camera)
        self.lImgRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lImgRate.setObjectName("lImgRate")
        self.gridlayout.addWidget(self.lImgRate, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.Camera)
        self.label_14.setObjectName("label_14")
        self.gridlayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.lImgCounter = QtGui.QLabel(self.Camera)
        self.lImgCounter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lImgCounter.setObjectName("lImgCounter")
        self.gridlayout.addWidget(self.lImgCounter, 4, 1, 1, 1)
        self.vboxlayout.addWidget(self.Camera)
        self.Parameters = QtGui.QGroupBox(self.layoutWidget)
        self.Parameters.setObjectName("Parameters")
        self.gridlayout1 = QtGui.QGridLayout(self.Parameters)
        self.gridlayout1.setObjectName("gridlayout1")
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setObjectName("gridlayout2")
        self.label = QtGui.QLabel(self.Parameters)
        self.label.setMinimumSize(QtCore.QSize(65, 0))
        self.label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label.setObjectName("label")
        self.gridlayout2.addWidget(self.label, 0, 0, 1, 1)
        self.leExpTime = QtGui.QLineEdit(self.Parameters)
        self.leExpTime.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leExpTime.setObjectName("leExpTime")
        self.gridlayout2.addWidget(self.leExpTime, 0, 1, 1, 1)
        self.lExpTime = QtGui.QLabel(self.Parameters)
        self.lExpTime.setMinimumSize(QtCore.QSize(35, 0))
        self.lExpTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lExpTime.setObjectName("lExpTime")
        self.gridlayout2.addWidget(self.lExpTime, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.Parameters)
        self.label_3.setMinimumSize(QtCore.QSize(65, 0))
        self.label_3.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridlayout2.addWidget(self.label_3, 1, 0, 1, 1)
        self.leExpPeriod = QtGui.QLineEdit(self.Parameters)
        self.leExpPeriod.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leExpPeriod.setObjectName("leExpPeriod")
        self.gridlayout2.addWidget(self.leExpPeriod, 1, 1, 1, 1)
        self.lExpPeriod = QtGui.QLabel(self.Parameters)
        self.lExpPeriod.setMinimumSize(QtCore.QSize(35, 0))
        self.lExpPeriod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lExpPeriod.setObjectName("lExpPeriod")
        self.gridlayout2.addWidget(self.lExpPeriod, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.Parameters)
        self.label_5.setMinimumSize(QtCore.QSize(65, 0))
        self.label_5.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridlayout2.addWidget(self.label_5, 2, 0, 1, 1)
        self.leGain = QtGui.QLineEdit(self.Parameters)
        self.leGain.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leGain.setObjectName("leGain")
        self.gridlayout2.addWidget(self.leGain, 2, 1, 1, 1)
        self.lGain = QtGui.QLabel(self.Parameters)
        self.lGain.setMinimumSize(QtCore.QSize(35, 0))
        self.lGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lGain.setObjectName("lGain")
        self.gridlayout2.addWidget(self.lGain, 2, 2, 1, 1)
        self.gridlayout1.addLayout(self.gridlayout2, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.Parameters)
        self.ROI = QtGui.QGroupBox(self.layoutWidget)
        self.ROI.setObjectName("ROI")
        self.gridlayout3 = QtGui.QGridLayout(self.ROI)
        self.gridlayout3.setObjectName("gridlayout3")
        self.gridlayout4 = QtGui.QGridLayout()
        self.gridlayout4.setObjectName("gridlayout4")
        self.label_28 = QtGui.QLabel(self.ROI)
        self.label_28.setMinimumSize(QtCore.QSize(65, 0))
        self.label_28.setObjectName("label_28")
        self.gridlayout4.addWidget(self.label_28, 0, 0, 1, 1)
        self.leRoiXStart = QtGui.QLineEdit(self.ROI)
        self.leRoiXStart.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leRoiXStart.setObjectName("leRoiXStart")
        self.gridlayout4.addWidget(self.leRoiXStart, 0, 1, 1, 1)
        self.lRoiXStart = QtGui.QLabel(self.ROI)
        self.lRoiXStart.setMinimumSize(QtCore.QSize(35, 0))
        self.lRoiXStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRoiXStart.setObjectName("lRoiXStart")
        self.gridlayout4.addWidget(self.lRoiXStart, 0, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.ROI)
        self.label_25.setMinimumSize(QtCore.QSize(65, 0))
        self.label_25.setObjectName("label_25")
        self.gridlayout4.addWidget(self.label_25, 1, 0, 1, 1)
        self.leRoiXSize = QtGui.QLineEdit(self.ROI)
        self.leRoiXSize.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leRoiXSize.setObjectName("leRoiXSize")
        self.gridlayout4.addWidget(self.leRoiXSize, 1, 1, 1, 1)
        self.lRoiXSize = QtGui.QLabel(self.ROI)
        self.lRoiXSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRoiXSize.setObjectName("lRoiXSize")
        self.gridlayout4.addWidget(self.lRoiXSize, 1, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.ROI)
        self.label_24.setMinimumSize(QtCore.QSize(65, 0))
        self.label_24.setObjectName("label_24")
        self.gridlayout4.addWidget(self.label_24, 2, 0, 1, 1)
        self.leRoiYStart = QtGui.QLineEdit(self.ROI)
        self.leRoiYStart.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leRoiYStart.setObjectName("leRoiYStart")
        self.gridlayout4.addWidget(self.leRoiYStart, 2, 1, 1, 1)
        self.lRoiYStart = QtGui.QLabel(self.ROI)
        self.lRoiYStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRoiYStart.setObjectName("lRoiYStart")
        self.gridlayout4.addWidget(self.lRoiYStart, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.ROI)
        self.label_13.setMinimumSize(QtCore.QSize(65, 0))
        self.label_13.setObjectName("label_13")
        self.gridlayout4.addWidget(self.label_13, 3, 0, 1, 1)
        self.leRoiYSize = QtGui.QLineEdit(self.ROI)
        self.leRoiYSize.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leRoiYSize.setObjectName("leRoiYSize")
        self.gridlayout4.addWidget(self.leRoiYSize, 3, 1, 1, 1)
        self.lRoiYSize = QtGui.QLabel(self.ROI)
        self.lRoiYSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lRoiYSize.setObjectName("lRoiYSize")
        self.gridlayout4.addWidget(self.lRoiYSize, 3, 2, 1, 1)
        self.gridlayout3.addLayout(self.gridlayout4, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.ROI)
        self.Binning = QtGui.QGroupBox(self.layoutWidget)
        self.Binning.setObjectName("Binning")
        self.gridlayout5 = QtGui.QGridLayout(self.Binning)
        self.gridlayout5.setObjectName("gridlayout5")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_15 = QtGui.QLabel(self.Binning)
        self.label_15.setMinimumSize(QtCore.QSize(65, 0))
        self.label_15.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_15.setObjectName("label_15")
        self.hboxlayout.addWidget(self.label_15)
        self.leBinX = QtGui.QLineEdit(self.Binning)
        self.leBinX.setMaximumSize(QtCore.QSize(75, 16777215))
        self.leBinX.setObjectName("leBinX")
        self.hboxlayout.addWidget(self.leBinX)
        self.lBinX = QtGui.QLabel(self.Binning)
        self.lBinX.setMinimumSize(QtCore.QSize(35, 0))
        self.lBinX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lBinX.setObjectName("lBinX")
        self.hboxlayout.addWidget(self.lBinX)
        self.gridlayout5.addLayout(self.hboxlayout, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.Binning)
        self.Crosses = QtGui.QGroupBox(self.layoutWidget)
        self.Crosses.setMinimumSize(QtCore.QSize(0, 164))
        self.Crosses.setObjectName("Crosses")
        self.gridlayout6 = QtGui.QGridLayout(self.Crosses)
        self.gridlayout6.setObjectName("gridlayout6")
        self.gridlayout7 = QtGui.QGridLayout()
        self.gridlayout7.setObjectName("gridlayout7")
        self.label_2 = QtGui.QLabel(self.Crosses)
        self.label_2.setObjectName("label_2")
        self.gridlayout7.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.Crosses)
        self.label_6.setObjectName("label_6")
        self.gridlayout7.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.Crosses)
        self.label_7.setObjectName("label_7")
        self.gridlayout7.addWidget(self.label_7, 1, 0, 1, 1)
        self.leCross1X = QtGui.QLineEdit(self.Crosses)
        self.leCross1X.setMaximumSize(QtCore.QSize(65, 16777215))
        self.leCross1X.setObjectName("leCross1X")
        self.gridlayout7.addWidget(self.leCross1X, 1, 1, 1, 1)
        self.leCross2X = QtGui.QLineEdit(self.Crosses)
        self.leCross2X.setMaximumSize(QtCore.QSize(65, 16777215))
        self.leCross2X.setObjectName("leCross2X")
        self.gridlayout7.addWidget(self.leCross2X, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.Crosses)
        self.label_8.setObjectName("label_8")
        self.gridlayout7.addWidget(self.label_8, 2, 0, 1, 1)
        self.leCross1Y = QtGui.QLineEdit(self.Crosses)
        self.leCross1Y.setMaximumSize(QtCore.QSize(65, 16777215))
        self.leCross1Y.setObjectName("leCross1Y")
        self.gridlayout7.addWidget(self.leCross1Y, 2, 1, 1, 1)
        self.leCross2Y = QtGui.QLineEdit(self.Crosses)
        self.leCross2Y.setMaximumSize(QtCore.QSize(65, 16777215))
        self.leCross2Y.setObjectName("leCross2Y")
        self.gridlayout7.addWidget(self.leCross2Y, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.Crosses)
        self.label_11.setObjectName("label_11")
        self.gridlayout7.addWidget(self.label_11, 3, 0, 1, 1)
        self.cbCross1Color = QtGui.QComboBox(self.Crosses)
        self.cbCross1Color.setMaximumSize(QtCore.QSize(65, 16777215))
        self.cbCross1Color.setObjectName("cbCross1Color")
        self.gridlayout7.addWidget(self.cbCross1Color, 3, 1, 1, 1)
        self.cbCross2Color = QtGui.QComboBox(self.Crosses)
        self.cbCross2Color.setMaximumSize(QtCore.QSize(65, 16777215))
        self.cbCross2Color.setObjectName("cbCross2Color")
        self.gridlayout7.addWidget(self.cbCross2Color, 3, 2, 1, 1)
        self.gridlayout6.addLayout(self.gridlayout7, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.Crosses)
        self.Modes = QtGui.QGroupBox(self.layoutWidget)
        self.Modes.setObjectName("Modes")
        self.gridlayout8 = QtGui.QGridLayout(self.Modes)
        self.gridlayout8.setObjectName("gridlayout8")
        self.gridlayout9 = QtGui.QGridLayout()
        self.gridlayout9.setObjectName("gridlayout9")
        self.label_22 = QtGui.QLabel(self.Modes)
        self.label_22.setObjectName("label_22")
        self.gridlayout9.addWidget(self.label_22, 0, 0, 1, 1)
        self.cbImageMode = QtGui.QComboBox(self.Modes)
        self.cbImageMode.setObjectName("cbImageMode")
        self.gridlayout9.addWidget(self.cbImageMode, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.Modes)
        self.label_23.setObjectName("label_23")
        self.gridlayout9.addWidget(self.label_23, 1, 0, 1, 1)
        self.cbTriggerMode = QtGui.QComboBox(self.Modes)
        self.cbTriggerMode.setObjectName("cbTriggerMode")
        self.gridlayout9.addWidget(self.cbTriggerMode, 1, 1, 1, 1)
        self.gridlayout8.addLayout(self.gridlayout9, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.Modes)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.bStart = QtGui.QPushButton(self.layoutWidget)
        self.bStart.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bStart.setObjectName("bStart")
        self.hboxlayout1.addWidget(self.bStart)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.bStop = QtGui.QPushButton(self.layoutWidget)
        self.bStop.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bStop.setObjectName("bStop")
        self.hboxlayout2.addWidget(self.bStop)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem3)
        self.vboxlayout.addLayout(self.hboxlayout2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem4)

        self.retranslateUi(GigEImageViewer)
        QtCore.QMetaObject.connectSlotsByName(GigEImageViewer)

    def retranslateUi(self, GigEImageViewer):
        GigEImageViewer.setWindowTitle(QtGui.QApplication.translate("GigEImageViewer", "Prosilica GC1350C Image Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.Camera.setTitle(QtGui.QApplication.translate("GigEImageViewer", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("GigEImageViewer", "Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_connected.setText(QtGui.QApplication.translate("GigEImageViewer", "NO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("GigEImageViewer", "Display Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rate.setText(QtGui.QApplication.translate("GigEImageViewer", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("GigEImageViewer", "Frame Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.lImgRate.setText(QtGui.QApplication.translate("GigEImageViewer", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("GigEImageViewer", "Counter", None, QtGui.QApplication.UnicodeUTF8))
        self.lImgCounter.setText(QtGui.QApplication.translate("GigEImageViewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.Parameters.setTitle(QtGui.QApplication.translate("GigEImageViewer", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GigEImageViewer", "Exp Time", None, QtGui.QApplication.UnicodeUTF8))
        self.lExpTime.setText(QtGui.QApplication.translate("GigEImageViewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GigEImageViewer", "Period", None, QtGui.QApplication.UnicodeUTF8))
        self.lExpPeriod.setText(QtGui.QApplication.translate("GigEImageViewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GigEImageViewer", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.lGain.setText(QtGui.QApplication.translate("GigEImageViewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ROI.setTitle(QtGui.QApplication.translate("GigEImageViewer", "ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("GigEImageViewer", "X Start", None, QtGui.QApplication.UnicodeUTF8))
        self.lRoiXStart.setText(QtGui.QApplication.translate("GigEImageViewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("GigEImageViewer", "X Size", None, QtGui.QApplication.UnicodeUTF8))
        self.lRoiXSize.setText(QtGui.QApplication.translate("GigEImageViewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("GigEImageViewer", "Y Start", None, QtGui.QApplication.UnicodeUTF8))
        self.lRoiYStart.setText(QtGui.QApplication.translate("GigEImageViewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("GigEImageViewer", "Y Size", None, QtGui.QApplication.UnicodeUTF8))
        self.lRoiYSize.setText(QtGui.QApplication.translate("GigEImageViewer", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.Binning.setTitle(QtGui.QApplication.translate("GigEImageViewer", "Binning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("GigEImageViewer", "X, Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lBinX.setText(QtGui.QApplication.translate("GigEImageViewer", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.Crosses.setTitle(QtGui.QApplication.translate("GigEImageViewer", "Crosses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GigEImageViewer", "Cross 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GigEImageViewer", "Cross 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GigEImageViewer", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("GigEImageViewer", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("GigEImageViewer", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.Modes.setTitle(QtGui.QApplication.translate("GigEImageViewer", "Modes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("GigEImageViewer", "Image Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("GigEImageViewer", "Trigger Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.bStart.setText(QtGui.QApplication.translate("GigEImageViewer", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.bStop.setText(QtGui.QApplication.translate("GigEImageViewer", "Stop", None, QtGui.QApplication.UnicodeUTF8))

